// Code generated by joker. DO NOT EDIT.
// Code generated by joker. DO NOT EDIT.
// Code generated by joker. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

type UserEntity struct{
	DB *gorm.DB
}

func NewUserModel(db *gorm.DB) *UserEntity {
	return &UserEntity{
		DB:db,
	}
}

// 根据id查询单条
func (entity *UserEntity) GetById(id int32) (info *User,err error) {
	err = entity.DB.Model(User{}).
		Limit(1).
		Find(&info, id).Error
	return info, err
}

// 根据条件查询
func (entity *UserEntity) GetMapWhere(where map[string]interface{}, fields ...string) (list []map[string]interface{}, err error) {
	db := entity.DB.Model(User{})
	if len(fields) > 0 {
		db = db.Select(fields)
	}
	if where != nil {
		db = db.Where(where)
	}
	err = db.Find(&list).Error

	return list, err
}