version: "3.2"

networks:
  es:

services:

  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    restart: always
    volumes:                                  # 数据卷挂载路径设置,将本机目录映射到容器目录
      - /docker/compose/es/data:/usr/share/elasticsearch/data:Z
      - /docker/compose/es/logs:/usr/share/elasticsearch/logs:Z
      - /docker/compose/es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:Z
      - /docker/compose/es/plugins:/usr/share/elasticsearch/plugins:Z
    ports:
      - 9200:9200
      - 9300:9300
    privileged: true
    environment:
      # 开启内存锁定
      - bootstrap.memory_lock=true
      # 修改jvm内存
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - TAKE_FILE_OWNERSHIP=true
     # 指定单节点启动
      - discovery.type=single-node
    ulimits:
      # 取消内存相关限制  用于开启内存锁定
     memlock:
        soft: -1
        hard: -1
    networks:
      - es

  kibana:

    image: kibana:7.6.2
    container_name: kibana
    privileged: true
    restart: always
    volumes:
      - /docker/compose/es/config/kibana.yml:/usr/share/kibana/config/kibana.yml:Z
    ports:
      - 5601:5601
    networks:
      - es
