version: '3.1'

networks:
  zk-net:
    # 网络名
    name: zk-net
    driver: bridge

services:
  # zookeeper集群
  zoo1:
    image: zookeeper:3.8.0
    container_name: zoo1 # 容器名称
    # restart: always # 开机自启
    hostname: zoo1 # 主机名
    ports:
      - 2181:2181 # 端口号
    environment:
      ZOO_MY_ID: 1
      # ZOO_SERVERS: server.1=zoo1:2888:3888;2181
    networks:
      - zk-net
  # kafka集群
  kafka1:
    image: 'bitnami/kafka:3.0.0'
    container_name: kafka1
    hostname: kafka1
    networks:
      - zk-net
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181/kafka
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zoo1
  kafka2:
    image: 'bitnami/kafka:3.0.0'
    container_name: kafka2
    hostname: kafka2
    networks:
      - zk-net
    ports:
      - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181/kafka
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zoo1
  kafka3:
    image: 'bitnami/kafka:3.0.0'
    container_name: kafka3
    hostname: kafka3
    networks:
      - zk-net
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181/kafka
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9094
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zoo1
  eagle:
    image: rottenleaf/kafka-eagle:2.0.3
    container_name: eagle
    volumes:
      - ./conf/system-config3.properties:/kafka-eagle/conf/system-config.properties
      # - /etc/localtime:/etc/localtime
    environment:
      - EFAK_CLUSTER_ZK_LIST=zoo1:2181 # 所有的做时间同步宿主机 要不然会有时间问题 
      - TZ=Asia/Shanghai
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - 8048:8048
    networks:
      - zk-net